[project]
name = "lokin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=25.1.0",
    "aiohttp>=3.13.3",
    "audioop-lts>=0.2.2",
    "docstring-parser>=0.17.0",
    "fastapi>=0.129.0",
    "langchain>=1.2.10",
    "loguru>=0.7.3",
    "numpy>=2.4.2",
    "onnxruntime>=1.24.1",
    "openai>=2.21.0",
    "opentelemetry-api>=1.39.1",
    "pillow>=12.1.1",
    "pyloudnorm>=0.2.0",
    "python-dotenv>=1.2.1",
    "soxr>=1.0.0",
    "sympy>=1.14.0",
    "transformers>=5.1.0",
]
